# package description
[package]
name = "wako_log_viewer"
version = "1.1.7"
edition = "2024"
description = "GUI viewer/filter/exporter for WAKO point-panel bout logs"
repository = "https://github.com/matas-noreika/wako-log-viewer"

# project dependencies
[dependencies]
eframe = "0.36"
egui = "0.36"
rfd = "0.17"
chrono = "0.4"
regex = "1"
markdown2pdf = "1.6.0"

# release profile configurations
[profile.release]
opt-level = 3            # Maximize performance for heavy egui math/rendering
lto = "fat"              # Perform Link-Time Optimization across all crates
codegen-units = 1        # Reduce parallel compilation blocks to maximize optimization
panic = "abort"          # Remove panic unwinding (cuts out significant code bloat)
strip = true             # Strip symbols and debug info automatically (huge size reduction)

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"

# build target configurations
[target.x86_64-pc-windows-gnu]
linker = "cargo-zigbuild"
